import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';

import DescriptWithImg from '@/client/components/descript-with-img';
import { ABOUT_ME } from '@/data/about-me';
import { DescriptionWithImage } from '@/types/index';

type AboutProps = {
	aboutMe: DescriptionWithImage;
};

const About: NextPage<AboutProps> = ({ aboutMe }) => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<div className='bg-secondary'>
					<section id='about-me' style={{ maxWidth: '1200px' }} className='mx-auto my-0 px-3 py-5'>
						<h2 className='text-info fw-bold mb-3'>About Me</h2>
						<DescriptWithImg item={aboutMe} imageLeft />
					</section>
				</div>
			</main>
		</div>
	);
};

export default About;

export const getStaticProps: GetStaticProps = () => ({
	props: {
		aboutMe: ABOUT_ME,
	},
});
