import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import Card from 'react-bootstrap/Card';

import { Education, Employment } from '../types';
import EmployHistory from '../client/components/employ-history';
import Notes from '../client/components/notes';
import { EDUCATION, INTERNSHIPS } from '../data/resume-data';

type EducationProps = {
	education: Education[];
	internships: Employment[];
};

const EducationSection: NextPage<EducationProps> = ({ education, internships }) => (
	<div>
		<Head>
			<title>Create Next App</title>
			<meta name='description' content='Generated by create next app' />
			<link rel='icon' href='/favicon.ico' />
		</Head>

		<div className='bg-danger'>
			<section id='education' style={{ maxWidth: '1200px' }} className='mx-auto my-0 px-3 py-5'>
				<h2 className='text-primary mb-3'>Education</h2>
				{education.map(school => (
					<>
						<div className='d-flex justify-content-between' key={school.schoolName}>
							<div className='d-block'>
								<Card.Title className='text-warning'>{school.schoolName}</Card.Title>
								<Card.Subtitle className='text-white'>
									{school.city}, {school.state}
								</Card.Subtitle>
							</div>
							<div className='text-white'>Graduated {school.gradDate}</div>
						</div>
						<div style={{ maxWidth: '800px' }} className='mx-auto'>
							<Notes notes={school.highlights} />
						</div>
					</>
				))}
				<h3 className='h5 text-warning'>Internships</h3>
				<EmployHistory history={internships} bgColor='danger' />
			</section>
		</div>
	</div>
);

export default EducationSection;

export const getStaticProps: GetStaticProps = () => ({
	props: {
		education: EDUCATION,
		internships: INTERNSHIPS,
	},
});
