import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';

import ContactSection from '@/client/sections/contact';
import IntroSection from '@/client/sections/intro';
import EducationSection from '@/client/sections/education';
import ExperienceSection from '@/client/sections/experience';
import { EDUCATION, EMPLOYMENT_HISTORY, INTERNSHIPS } from '@/data/resume-data';
import { Education, Employment } from '@/types/index';

type HomeProps = {
	education: Education[];
	employHistory: Employment[];
	internships: Employment[];
};

const Home: NextPage<HomeProps> = ({ education, employHistory, internships }) => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<IntroSection />
				<ExperienceSection employHistory={employHistory} />
				<EducationSection education={education} internships={internships} />
				<ContactSection />
			</main>
		</div>
	);
};

export default Home;

export const getStaticProps: GetStaticProps = () => ({
	props: {
		education: EDUCATION,
		employHistory: EMPLOYMENT_HISTORY,
		internships: INTERNSHIPS,
	},
});
