import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';

import { Employment } from '../types';
import EmployHistory from '../client/components/employ-history';
import { EMPLOYMENT_HISTORY } from '../data/resume-data';

type ResumeProps = {
	employHistory: Employment[];
};

const Resume: NextPage<ResumeProps> = ({ employHistory }) => (
	<div>
		<Head>
			<title>Create Next App</title>
			<meta name='description' content='Generated by create next app' />
			<link rel='icon' href='/favicon.ico' />
		</Head>

		<EmployHistory history={employHistory} />
	</div>
);

export default Resume;

export const getStaticProps: GetStaticProps = () => ({
	props: {
		employHistory: EMPLOYMENT_HISTORY,
	},
});
