import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';

import EmployHistory from '@/client/components/employ-history';
import { EMPLOYMENT_HISTORY } from '@/data/resume-data';
import { Employment } from '@/types/index';

type ProfExperProps = {
	employHistory: Employment[];
};

const ProfExper: NextPage<ProfExperProps> = ({ employHistory }) => (
	<div>
		<Head>
			<title>Create Next App</title>
			<meta name='description' content='Generated by create next app' />
			<link rel='icon' href='/favicon.ico' />
		</Head>

		<div className='bg-secondary'>
			<section
				id='prof-experience'
				style={{ maxWidth: '1200px' }}
				className='mx-auto my-0 px-3 py-5'
			>
				<h2 className='text-primary mb-3'>Professional Experience</h2>
				<EmployHistory history={employHistory} bgColor='secondary' />
			</section>
		</div>
	</div>
);

export default ProfExper;

export const getStaticProps: GetStaticProps = () => ({
	props: {
		employHistory: EMPLOYMENT_HISTORY,
	},
});
